//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLoop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLoop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Base {
            get {
                object obj = ResourceManager.GetObject("Base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dank_background {
            get {
                object obj = ResourceManager.GetObject("dank_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dank_background1 {
            get {
                object obj = ResourceManager.GetObject("dank_background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dank_kid {
            get {
                object obj = ResourceManager.GetObject("dank_kid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dank_shrek {
            get {
                object obj = ResourceManager.GetObject("dank_shrek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap floor_tile_texture {
            get {
                object obj = ResourceManager.GetObject("floor_tile_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap illerminaty {
            get {
                object obj = ResourceManager.GetObject("illerminaty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Level&gt;
        ///  &lt;Size&gt;
        ///    &lt;Width&gt;30&lt;/Width&gt;
        ///    &lt;Height&gt;20&lt;/Height&gt;
        ///  &lt;/Size&gt;
        ///  &lt;Tiles&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;0&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;1&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;2&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;3&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;4&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;5&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;6&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;7&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;8&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;9&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;10&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;11&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;12&quot; /&gt;
        ///    &lt;Muur x=&quot;0&quot; y=&quot;13&quot; /&gt;
        ///    &lt;Muur x=&quot;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Man_slayer {
            get {
                object obj = ResourceManager.GetObject("Man_slayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static string Level2 { get; internal set; }
    }
}
